if filereadable('$HCHTR_HOME/repos/env/vim/plugins.vim')
    source $HCHTR_HOME/repos/env/vim/plugins.vim
endif

if filereadable('$HCHTR_HOME/repos/env/vim/settings.vim')
    source $HCHTR_HOME/repos/env/vim/settings.vim
endif

if filereadable('$HCHTR_HOME/repos/env/vim/keymaps.vim')
    source $HCHTR_HOME/repos/env/vim/keymaps.vim
endif

if filereadable('$HCHTR_HOME/repos/env/vim/local.vim')
    source $HCHTR_HOME/repos/env/vim/local.vim
endif
