let g:REPO_VIM_PATH = expand('$HCHTR_HOME') . '/repos/env/vim'

if filereadable(g:REPO_VIM_PATH . '/plugins.vim')
    execute 'source ' . g:REPO_VIM_PATH . '/plugins.vim'
endif

if filereadable(g:REPO_VIM_PATH . '/settings.vim')
    execute 'source ' . g:REPO_VIM_PATH . '/settings.vim'
endif

if filereadable(g:REPO_VIM_PATH . '/keymaps.vim')
    execute 'source ' . g:REPO_VIM_PATH . '/keymaps.vim'
endif

if filereadable(g:REPO_VIM_PATH . '/local.vim')
    execute 'source ' . g:REPO_VIM_PATH . '/local.vim'
endif
