syntax on
filetype on

set autoread

set tabstop=4
set shiftwidth=4
set autoindent
set expandtab

set wildmenu

set relativenumber 
set termguicolors
colo sorbet 

inoremap ( ()<Esc>i
inoremap [ []<Esc>i
inoremap { {}<Esc>i
inoremap " ""<Esc>i
inoremap ' ''<Esc>i

set hlsearch
set incsearch
set ignorecase

set guioptions+=m " -=
set guioptions+=T " -=
set guioptions-=r " -=
